"use client";

import { useEffect, useState } from "react";

type Tool = "typing" | "vat" | "emi" | "land" | "units" | "bmi" | "age";
type NewsItem = { source: string; title: string; url: string };

const newsSeed = [["Onlinekhabar", "नेपालका आजका मुख्य समाचार", "https://www.onlinekhabar.com/"], ["Setopati", "राजनीति, समाज र अर्थतन्त्रका ताजा खबर", "https://www.setopati.com/"], ["Kantipur", "नेपाल तथा विश्वका महत्वपूर्ण समाचार", "https://ekantipur.com/"], ["Baahrakhari", "ब्रेकिङ र बहसका विषय", "https://baahrakhari.com/"], ["TechPana", "नेपालको प्रविधि र डिजिटल समाचार", "https://techpana.com/"]];
const romanized: Record<string, string> = { namaste:"नमस्ते", dhanyabad:"धन्यवाद", dhanyavaad:"धन्यवाद", mero:"मेरो", naam:"नाम", ram:"राम", ho:"हो", nepal:"नेपाल", kathmandu:"काठमाडौं", sanchai:"सञ्चै", cha:"छ", tapai:"तपाईं", ma:"म", ra:"र", ko:"को", lai:"लाई", maile:"मैले", aaja:"आज", bholi:"भोलि", pani:"पानी", ghar:"घर", school:"स्कुल", kitab:"किताब", yo:"यो", hoina:"होइन" };
const n = (v: string) => Math.max(0, Number(v) || 0);
const typeNepali = (text: string) => text.split(/(\s+|[,.!?])/).map(word => romanized[word.toLowerCase()] || word).join("");

function ToolPanel({ tool }: { tool: Tool }) {
  const [base, setBase] = useState("1000"); const [vatMode, setVatMode] = useState<"add"|"included">("add");
  const [principal, setPrincipal] = useState("5000000"), [rate, setRate] = useState("10"), [years, setYears] = useState("20");
  const [land, setLand] = useState("1"), [landUnit, setLandUnit] = useState("ropani");
  const [value, setValue] = useState("1"), [from, setFrom] = useState("ft"), [to, setTo] = useState("m");
  const [weight, setWeight] = useState("60"), [height, setHeight] = useState("170"), [birth, setBirth] = useState("2000-01-01");
  const [roman, setRoman] = useState("mero naam Ram ho"), [copied, setCopied] = useState(false);
  const Field = ({ label, value, onChange, type="number" }: { label:string; value:string; onChange:(x:string)=>void; type?:string }) => <label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>;
  const vat = n(base), vatAmount = vatMode === "add" ? vat*.13 : vat*13/113, total = vatMode === "add" ? vat+vatAmount : vat;
  const mRate=n(rate)/1200, months=Math.max(1,n(years)*12), emi=mRate ? n(principal)*mRate*Math.pow(1+mRate,months)/(Math.pow(1+mRate,months)-1) : n(principal)/months;
  const landFactors: Record<string,number> = { ropani:5476, aana:342.25, paisa:85.5625, daam:21.390625, sqft:1, sqm:10.7639104, acre:43560, hectare:107639.104 };
  const sqft=n(land)*landFactors[landUnit]; const factors:Record<string,number>={mm:.001,cm:.01,m:1,km:1000,in:.0254,ft:.3048,yd:.9144,mile:1609.344}; const converted=n(value)*factors[from]/factors[to];
  const bmi=n(weight)/Math.pow(n(height)/100||1,2), days=Math.max(0,Math.floor((Date.now()-new Date(birth).getTime())/86400000));
  const result = (items: [string,string][]) => <div className="results">{items.map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>;
  if(tool === "typing") { const output=typeNepali(roman); return <section className="tool-panel"><p className="eyebrow">नेपाली लेख्नुहोस्</p><h2>Romanized Nepali Typing</h2><p>Common Romanized Nepali words convert instantly. A full verified Preeti font map will be added separately; this page does not pretend to convert it yet.</p><div className="typing-grid"><label>English/Romanized Nepali<textarea value={roman} onChange={e=>setRoman(e.target.value)}/></label><label>नेपाली Unicode<textarea value={output} readOnly/></label></div><button className="primary" onClick={async()=>{await navigator.clipboard?.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),1600)}}>{copied?"कपी भयो":"Unicode कपी गर्नुहोस्"}</button></section>; }
  if(tool === "vat") return <section className="tool-panel"><p className="eyebrow">१३% VAT</p><h2>VAT क्याल्कुलेटर</h2><div className="choice-row"><button className={vatMode==="add"?"active":""} onClick={()=>setVatMode("add")}>VAT थप्नुहोस्</button><button className={vatMode==="included"?"active":""} onClick={()=>setVatMode("included")}>VAT सहित रकम</button></div><div className="form-grid"><Field label="रकम (रु.)" value={base} onChange={setBase}/></div>{result([["VAT रकम",`रु. ${vatAmount.toLocaleString("en-US",{maximumFractionDigits:2})}`],["जम्मा रकम",`रु. ${total.toLocaleString("en-US",{maximumFractionDigits:2})}`]])}</section>;
  if(tool === "emi") return <section className="tool-panel"><p className="eyebrow">ऋण योजना</p><h2>EMI क्याल्कुलेटर</h2><div className="form-grid"><Field label="ऋण रकम (रु.)" value={principal} onChange={setPrincipal}/><Field label="ब्याज दर (% वार्षिक)" value={rate} onChange={setRate}/><Field label="अवधि (वर्ष)" value={years} onChange={setYears}/></div>{result([["मासिक EMI",`रु. ${emi.toLocaleString("en-US",{maximumFractionDigits:0})}`],["कुल भुक्तानी",`रु. ${(emi*months).toLocaleString("en-US",{maximumFractionDigits:0})}`],["कुल ब्याज",`रु. ${(emi*months-n(principal)).toLocaleString("en-US",{maximumFractionDigits:0})}`]])}</section>;
  if(tool === "land") return <section className="tool-panel"><p className="eyebrow">जग्गा हिसाब</p><h2>नेपाल जग्गा युनिट कन्भर्टर</h2><div className="form-grid"><Field label="परिमाण" value={land} onChange={setLand}/><label>युनिट<select value={landUnit} onChange={e=>setLandUnit(e.target.value)}>{Object.keys(landFactors).map(x=><option key={x}>{x}</option>)}</select></label></div>{result([["वर्ग फिट",`${sqft.toLocaleString("en-US",{maximumFractionDigits:2})} sq ft`],["रोपनी",(sqft/5476).toLocaleString("en-US",{maximumFractionDigits:4})],["आना",(sqft/342.25).toLocaleString("en-US",{maximumFractionDigits:2})],["वर्ग मिटर",(sqft/10.7639104).toLocaleString("en-US",{maximumFractionDigits:2})]])}</section>;
  if(tool === "units") return <section className="tool-panel"><p className="eyebrow">दैनिक रूपान्तरण</p><h2>लम्बाइ युनिट कन्भर्टर</h2><div className="form-grid"><Field label="परिमाण" value={value} onChange={setValue}/><label>बाट<select value={from} onChange={e=>setFrom(e.target.value)}>{Object.keys(factors).map(x=><option key={x}>{x}</option>)}</select></label><label>मा<select value={to} onChange={e=>setTo(e.target.value)}>{Object.keys(factors).map(x=><option key={x}>{x}</option>)}</select></label></div>{result([["नतिजा",`${converted.toLocaleString("en-US",{maximumFractionDigits:6})} ${to}`]])}</section>;
  if(tool === "bmi") return <section className="tool-panel"><p className="eyebrow">स्वास्थ्य</p><h2>BMI क्याल्कुलेटर</h2><div className="form-grid"><Field label="तौल (kg)" value={weight} onChange={setWeight}/><Field label="उचाइ (cm)" value={height} onChange={setHeight}/></div>{result([["BMI",bmi.toFixed(1)],["स्थिति",bmi<18.5?"कम तौल":bmi<25?"सामान्य":bmi<30?"बढी तौल":"मोटोपना"]])}</section>;
  return <section className="tool-panel"><p className="eyebrow">उमेर</p><h2>Age क्याल्कुलेटर</h2><div className="form-grid"><Field label="जन्म मिति (AD)" value={birth} onChange={setBirth} type="date"/></div>{result([["उमेर",`${Math.floor(days/365.2425)} वर्ष`],["दिन",`${days.toLocaleString()} दिन`]])}</section>;
}

export default function Home() {
  const [tool,setTool]=useState<Tool>("vat"); const [headlines,setHeadlines]=useState<NewsItem[]>([]);
  useEffect(()=>{fetch("/api/news").then(r=>r.ok?r.json():[]).then(setHeadlines).catch(()=>undefined)},[]);
  const tools:{id:Tool;title:string;subtitle:string}[]=[{id:"typing",title:"नेपाली टाइपिङ",subtitle:"Romanized → Unicode"},{id:"vat",title:"VAT क्याल्कुलेटर",subtitle:"१३% तुरुन्त हिसाब"},{id:"emi",title:"EMI क्याल्कुलेटर",subtitle:"मासिक किस्ता"},{id:"land",title:"जग्गा कन्भर्टर",subtitle:"रोपनी, आना, sq ft"},{id:"units",title:"युनिट कन्भर्टर",subtitle:"ft, m, km"},{id:"bmi",title:"BMI क्याल्कुलेटर",subtitle:"तौल र उचाइ"},{id:"age",title:"उमेर क्याल्कुलेटर",subtitle:"AD जन्म मिति"}];
  return <main><header><a className="brand" href="#">नेपाल <span>टुल्स</span></a><nav><a href="#tools">टुलहरू</a><a href="#news">समाचार</a></nav></header><section className="hero"><div><p className="eyebrow">नेपालका लागि डिजिटल उपयोगिता</p><h1>कामका टुल, <em>साथै</em> सबैलाई जोड्ने ठाउँ।</h1><p className="sub">क्यालेन्डर, नेपाली टाइपिङ, कन्भर्टर र उपयोगी दैनिक हिसाब—एकै ठाउँमा।</p><div className="hero-buttons"><a className="primary" href="#tools">टुल छान्नुहोस्</a></div></div><aside className="calendar"><p>आजको मिति</p><strong>१३ भदौ २०८३, शुक्रबार</strong><span>August 28, 2026 · काठमाडौं</span><hr/><b>भाद्र शुक्ल पञ्चमी</b><small>सिद्धि · बव · स्वाती</small><div className="clock">१२:४३:४१ <i>PM</i></div></aside></section><section id="tools" className="tools"><div className="section-title"><div><p className="eyebrow">अहिले नै प्रयोग गर्नुहोस्</p><h2>दैनिक उपयोगी टुलहरू</h2></div></div><div className="tool-row">{tools.map(item=><button className={tool===item.id?"tool-card selected":"tool-card"} onClick={()=>setTool(item.id)} key={item.id}><b>{item.title}</b><span>{item.subtitle}</span></button>)}</div><ToolPanel tool={tool}/></section><section id="news" className="section-title"><div><p className="eyebrow">नेपालका चर्चित विषय</p><h2>ताजा समाचार</h2></div><a href="https://news.google.com/search?q=Nepal" target="_blank" rel="noreferrer">सबै समाचार हेर्नुहोस् ↗</a></section><section className="news-grid">{(headlines.length?headlines:newsSeed.map(([source,title,url])=>({source,title,url}))).map((item,i)=><a className="news" key={`${item.source}-${i}`} href={item.url} target="_blank" rel="noreferrer"><span>{item.source}</span><h3>{item.title}</h3><p>मूल प्रकाशकबाट प्रत्यक्ष पढ्नुहोस्</p><b>पढ्नुहोस् →</b></a>)}</section><footer><b>नेपाल टुल्स</b><span>विश्वसनीय स्रोतमा आधारित उपयोगी डिजिटल टुलहरू</span></footer></main>;
}
